/**
 * Config generation — translates the plugin's camelCase TypeScript config
 * into BitRouter's snake_case YAML format.
 *
 * BitRouter's config structure (from bitrouter-config/src/config.rs):
 *
 *   server:
 *     listen: "127.0.0.1:8787"
 *   providers:
 *     openai:
 *       api_key: "${OPENAI_API_KEY}"
 *       api_base: "https://..."
 *       env_prefix: "OPENAI"
 *       derives: "openai"
 *   models:
 *     fast:
 *       strategy: load_balance
 *       endpoints:
 *         - provider: openai
 *           model_id: gpt-4o-mini
 *
 * The plugin generates this YAML from the OpenClaw plugin config, then
 * writes it to a home directory that BitRouter reads on startup.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import * as YAML from "yaml";

import type {
  BitrouterPluginConfig,
  ProviderEntry,
  ModelEntry,
  OpenClawPluginApi,
} from "./types.js";
import { DEFAULTS } from "./types.js";

// ── YAML generation ──────────────────────────────────────────────────

/**
 * Generate a bitrouter.yaml string from the plugin config.
 *
 * Handles the camelCase → snake_case mapping and separates literal API
 * keys into a .env file (returned separately) to avoid secrets in YAML.
 */
export function generateConfig(config: BitrouterPluginConfig): {
  yaml: string;
  envVars: Record<string, string>;
} {
  const host = config.host ?? DEFAULTS.host;
  const port = config.port ?? DEFAULTS.port;

  // Build the YAML-serializable config object using BitRouter's field names.
  const yamlObj: Record<string, unknown> = {
    server: {
      listen: `${host}:${port}`,
    },
  };

  // Track literal API keys that should go into .env instead of YAML.
  const envVars: Record<string, string> = {};

  // --- Providers ---
  if (config.providers && Object.keys(config.providers).length > 0) {
    const providers: Record<string, Record<string, unknown>> = {};

    for (const [name, entry] of Object.entries(config.providers)) {
      const provider: Record<string, unknown> = {};

      if (entry.apiKey) {
        if (isEnvVarReference(entry.apiKey)) {
          // Already an env var reference like "${OPENAI_API_KEY}" — pass through.
          provider.api_key = entry.apiKey;
        } else {
          // Literal API key — store in .env and reference from YAML.
          const envVarName = resolveEnvVarName(name, entry);
          envVars[envVarName] = entry.apiKey;
          provider.api_key = `\${${envVarName}}`;
        }
      }

      if (entry.apiBase) provider.api_base = entry.apiBase;
      if (entry.envPrefix) provider.env_prefix = entry.envPrefix;
      if (entry.derives) provider.derives = entry.derives;

      providers[name] = provider;
    }

    yamlObj.providers = providers;
  }

  // --- Models ---
  if (config.models && Object.keys(config.models).length > 0) {
    const models: Record<string, Record<string, unknown>> = {};

    for (const [name, model] of Object.entries(config.models)) {
      const modelObj: Record<string, unknown> = {};

      if (model.strategy) {
        modelObj.strategy = model.strategy;
      }

      modelObj.endpoints = model.endpoints.map((ep) => {
        const endpoint: Record<string, unknown> = {
          provider: ep.provider,
          model_id: ep.modelId,
        };
        if (ep.apiKey) endpoint.api_key = ep.apiKey;
        if (ep.apiBase) endpoint.api_base = ep.apiBase;
        return endpoint;
      });

      models[name] = modelObj;
    }

    yamlObj.models = models;
  }

  const yaml =
    "# BitRouter configuration\n" +
    "# Generated by @bitrouter/openclaw-plugin\n\n" +
    YAML.stringify(yamlObj);

  return { yaml, envVars };
}

// ── File writing ─────────────────────────────────────────────────────

/**
 * Write bitrouter.yaml and .env to the given home directory.
 * Creates the directory structure if it doesn't exist.
 *
 * Returns the absolute path to the home directory.
 */
export function writeConfigToDir(
  config: BitrouterPluginConfig,
  homeDir: string
): string {
  // Ensure directory structure matches what BitRouter expects.
  fs.mkdirSync(homeDir, { recursive: true });
  fs.mkdirSync(path.join(homeDir, "run"), { recursive: true });
  fs.mkdirSync(path.join(homeDir, "logs"), { recursive: true });

  const { yaml, envVars } = generateConfig(config);

  // Write bitrouter.yaml
  fs.writeFileSync(path.join(homeDir, "bitrouter.yaml"), yaml, "utf-8");

  // Write .env if there are literal API keys
  if (Object.keys(envVars).length > 0) {
    const envContent =
      "# BitRouter environment variables\n" +
      "# Generated by @bitrouter/openclaw-plugin — do not commit.\n\n" +
      Object.entries(envVars)
        .map(([key, value]) => `${key}=${value}`)
        .join("\n") +
      "\n";
    fs.writeFileSync(path.join(homeDir, ".env"), envContent, "utf-8");
  }

  // Write .gitignore to protect secrets and runtime artifacts.
  const gitignorePath = path.join(homeDir, ".gitignore");
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, "logs/\nrun/\n.env\n", "utf-8");
  }

  return homeDir;
}

/**
 * Resolve the home directory for this plugin's BitRouter instance.
 *
 * Priority:
 * 1. OpenClaw's plugin data directory (isolated per-plugin)
 * 2. Fallback to os.tmpdir()/bitrouter-openclaw
 */
export function resolveHomeDir(api: OpenClawPluginApi): string {
  try {
    return path.join(api.getDataDir(), "bitrouter");
  } catch {
    return path.join(os.tmpdir(), "bitrouter-openclaw");
  }
}

// ── Helpers ──────────────────────────────────────────────────────────

/** Check if a string is an env var reference like "${OPENAI_API_KEY}". */
function isEnvVarReference(value: string): boolean {
  return /^\$\{[A-Z_][A-Z0-9_]*\}$/.test(value);
}

/**
 * Determine the env var name for a provider's API key.
 * Uses envPrefix if set, otherwise derives from the provider name.
 *
 * Examples:
 *   name="openai", envPrefix="OPENAI" → "OPENAI_API_KEY"
 *   name="my-company", envPrefix=undefined → "MY_COMPANY_API_KEY"
 */
function resolveEnvVarName(name: string, entry: ProviderEntry): string {
  const prefix =
    entry.envPrefix ?? name.toUpperCase().replace(/[^A-Z0-9]/g, "_");
  return `${prefix}_API_KEY`;
}
