/**
 * Config generation — translates the plugin's camelCase TypeScript config
 * into BitRouter's snake_case YAML format.
 *
 * BitRouter's config structure (from bitrouter-config/src/config.rs):
 *
 *   server:
 *     listen: "127.0.0.1:8787"
 *   providers:
 *     openai:
 *       api_key: "${OPENAI_API_KEY}"
 *       api_base: "https://..."
 *       env_prefix: "OPENAI"
 *       derives: "openai"
 *   models:
 *     fast:
 *       strategy: load_balance
 *       endpoints:
 *         - provider: openai
 *           model_id: gpt-4o-mini
 *
 * The plugin generates this YAML from the OpenClaw plugin config, then
 * writes it to a home directory that BitRouter reads on startup.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import * as YAML from "yaml";

import type {
  BitrouterPluginConfig,
  ProviderEntry,
  ModelEntry,
} from "./types.js";
import { DEFAULTS } from "./types.js";

// ── Well-known provider API base URLs ────────────────────────────────

/**
 * Canonical OpenAI-compatible base URLs for well-known providers.
 * Single source of truth — used by setup.ts (wizard) and service.ts (config gen).
 */
export const PROVIDER_API_BASES: Record<string, string> = {
  openrouter: "https://openrouter.ai/api/v1",
  openai: "https://api.openai.com/v1",
  anthropic: "https://api.anthropic.com/v1",
};

// ── Shared env-var helpers ───────────────────────────────────────────

/**
 * Derive an env-var key name from a provider name.
 * E.g. "openrouter" → "OPENROUTER_API_KEY", "my-company" → "MY_COMPANY_API_KEY"
 */
export function toEnvVarKey(providerName: string): string {
  return `${providerName.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_API_KEY`;
}

/**
 * Parse a .env file into a key→value Map.
 * Skips blank lines and # comments; splits on the first `=`.
 */
export function parseEnvFile(content: string): Map<string, string> {
  const entries = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx > 0) {
      entries.set(trimmed.slice(0, eqIdx).trim(), trimmed.slice(eqIdx + 1).trim());
    }
  }
  return entries;
}

/**
 * Serialize a key→value Map into .env file content with a standard header.
 */
export function serializeEnvFile(entries: Map<string, string>): string {
  const header =
    "# BitRouter environment variables\n" +
    "# Generated by @bitrouter/openclaw-plugin — do not commit.\n\n";
  const lines = Array.from(entries.entries())
    .map(([k, v]) => `${k}=${v}`)
    .join("\n");
  return header + lines + "\n";
}

// ── YAML generation ──────────────────────────────────────────────────

/**
 * Generate a bitrouter.yaml string from the plugin config.
 *
 * Handles the camelCase → snake_case mapping and separates literal API
 * keys into a .env file (returned separately) to avoid secrets in YAML.
 *
 * @param config - Plugin configuration
 * @param opts.inlineSecrets - When true, write literal API keys directly
 *   into the YAML instead of extracting them to a .env file. Used when
 *   BitRouter is started in no-db mode (Option B) where it cannot load
 *   an env file. The home dir is gitignored so this is acceptable locally.
 */
export function generateConfig(
  config: BitrouterPluginConfig,
  opts: { inlineSecrets?: boolean } = {}
): {
  yaml: string;
  envVars: Record<string, string>;
} {
  const host = config.host ?? DEFAULTS.host;
  const port = config.port ?? DEFAULTS.port;

  // Build the YAML-serializable config object using BitRouter's field names.
  const yamlObj: Record<string, unknown> = {
    server: {
      listen: `${host}:${port}`,
    },
  };

  // Track literal API keys that should go into .env instead of YAML.
  const envVars: Record<string, string> = {};

  // --- Providers ---
  if (config.providers && Object.keys(config.providers).length > 0) {
    const providers: Record<string, Record<string, unknown>> = {};

    for (const [name, entry] of Object.entries(config.providers)) {
      const provider: Record<string, unknown> = {};

      if (entry.apiKey) {
        if (isEnvVarReference(entry.apiKey)) {
          // Already an env var reference like "${OPENAI_API_KEY}" — pass through.
          provider.api_key = entry.apiKey;
        } else if (opts.inlineSecrets) {
          // No-db mode: write the key literally into YAML.
          // The home dir is gitignored; this is acceptable for local dev.
          provider.api_key = entry.apiKey;
        } else {
          // Literal API key — store in .env and reference from YAML.
          const envVarName = resolveEnvVarName(name, entry);
          envVars[envVarName] = entry.apiKey;
          provider.api_key = `\${${envVarName}}`;
        }
      }

      if (entry.apiBase) provider.api_base = entry.apiBase;
      if (entry.envPrefix) provider.env_prefix = entry.envPrefix;
      if (entry.derives) provider.derives = entry.derives;

      providers[name] = provider;
    }

    yamlObj.providers = providers;
  }

  // --- Models ---
  if (config.models && Object.keys(config.models).length > 0) {
    const models: Record<string, Record<string, unknown>> = {};

    for (const [name, model] of Object.entries(config.models)) {
      const modelObj: Record<string, unknown> = {};

      if (model.strategy) {
        modelObj.strategy = model.strategy;
      }

      modelObj.endpoints = model.endpoints.map((ep) => {
        const endpoint: Record<string, unknown> = {
          provider: ep.provider,
          model_id: ep.modelId,
        };
        if (ep.apiKey) endpoint.api_key = ep.apiKey;
        if (ep.apiBase) endpoint.api_base = ep.apiBase;
        return endpoint;
      });

      models[name] = modelObj;
    }

    yamlObj.models = models;
  }

  const yaml =
    "# BitRouter configuration\n" +
    "# Generated by @bitrouter/openclaw-plugin\n\n" +
    YAML.stringify(yamlObj);

  return { yaml, envVars };
}

// ── File writing ─────────────────────────────────────────────────────

/**
 * Write bitrouter.yaml and .env to the given home directory.
 * Creates the directory structure if it doesn't exist.
 *
 * Returns the absolute path to the home directory.
 */
export function writeConfigToDir(
  config: BitrouterPluginConfig,
  homeDir: string,
  opts: { inlineSecrets?: boolean } = {}
): string {
  // Ensure directory structure matches what BitRouter expects.
  fs.mkdirSync(homeDir, { recursive: true });
  fs.mkdirSync(path.join(homeDir, "run"), { recursive: true });
  fs.mkdirSync(path.join(homeDir, "logs"), { recursive: true });

  const { yaml, envVars } = generateConfig(config, opts);

  // Write bitrouter.yaml
  fs.writeFileSync(path.join(homeDir, "bitrouter.yaml"), yaml, "utf-8");

  // Write .env if there are literal API keys
  if (Object.keys(envVars).length > 0) {
    const envContent =
      "# BitRouter environment variables\n" +
      "# Generated by @bitrouter/openclaw-plugin — do not commit.\n\n" +
      Object.entries(envVars)
        .map(([key, value]) => `${key}=${value}`)
        .join("\n") +
      "\n";
    fs.writeFileSync(path.join(homeDir, ".env"), envContent, "utf-8");
  }

  // Write .gitignore to protect secrets and runtime artifacts.
  const gitignorePath = path.join(homeDir, ".gitignore");
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, "logs/\nrun/\n.env\n", "utf-8");
  }

  return homeDir;
}

/**
 * Resolve the home directory for this plugin's BitRouter instance.
 *
 * @param stateDir - The plugin's persistent state directory (from OpenClaw service context).
 */
export function resolveHomeDir(stateDir: string): string {
  return path.join(stateDir, "bitrouter");
}

// ── Helpers ──────────────────────────────────────────────────────────

/** Check if a string is an env var reference like "${OPENAI_API_KEY}". */
function isEnvVarReference(value: string): boolean {
  return /^\$\{[A-Z_][A-Z0-9_]*\}$/.test(value);
}

/**
 * Determine the env var name for a provider's API key.
 * Uses envPrefix if set, otherwise derives from the provider name.
 */
function resolveEnvVarName(name: string, entry: ProviderEntry): string {
  if (entry.envPrefix) return `${entry.envPrefix}_API_KEY`;
  return toEnvVarKey(name);
}
